// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.1
// source: proto/live.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 基础消息 ==========
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_live_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ========== 创建直播间 ==========
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_live_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRoomRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateRoomRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId        uint64                 `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,4,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	PushUrl       string                 `protobuf:"bytes,5,opt,name=push_url,json=pushUrl,proto3" json:"push_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_proto_live_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRoomResponse) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateRoomResponse) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *CreateRoomResponse) GetPushUrl() string {
	if x != nil {
		return x.PushUrl
	}
	return ""
}

// ========== 开始直播 ==========
type StartLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                       // 直播间标题（首次创建时用）
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                 // 分类（首次创建时用）
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"` // 封面图（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLiveRequest) Reset() {
	*x = StartLiveRequest{}
	mi := &file_proto_live_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveRequest) ProtoMessage() {}

func (x *StartLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveRequest.ProtoReflect.Descriptor instead.
func (*StartLiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{3}
}

func (x *StartLiveRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartLiveRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StartLiveRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *StartLiveRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type StartLiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId        uint64                 `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`            // 房间ID（新创建或已有）
	StreamKey     string                 `protobuf:"bytes,4,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`    // 推流密钥
	PushUrl       string                 `protobuf:"bytes,5,opt,name=push_url,json=pushUrl,proto3" json:"push_url,omitempty"`          // RTMP推流地址
	PlayUrl       string                 `protobuf:"bytes,6,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`          // HLS播放地址
	IsNewRoom     bool                   `protobuf:"varint,7,opt,name=is_new_room,json=isNewRoom,proto3" json:"is_new_room,omitempty"` // 是否新创建的房间
	FlvUrl        string                 `protobuf:"bytes,8,opt,name=flv_url,json=flvUrl,proto3" json:"flv_url,omitempty"`             // FLV播放地址
	WebrtcUrl     string                 `protobuf:"bytes,9,opt,name=webrtc_url,json=webrtcUrl,proto3" json:"webrtc_url,omitempty"`    // WebRTC播放地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLiveResponse) Reset() {
	*x = StartLiveResponse{}
	mi := &file_proto_live_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveResponse) ProtoMessage() {}

func (x *StartLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveResponse.ProtoReflect.Descriptor instead.
func (*StartLiveResponse) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{4}
}

func (x *StartLiveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StartLiveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartLiveResponse) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StartLiveResponse) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *StartLiveResponse) GetPushUrl() string {
	if x != nil {
		return x.PushUrl
	}
	return ""
}

func (x *StartLiveResponse) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *StartLiveResponse) GetIsNewRoom() bool {
	if x != nil {
		return x.IsNewRoom
	}
	return false
}

func (x *StartLiveResponse) GetFlvUrl() string {
	if x != nil {
		return x.FlvUrl
	}
	return ""
}

func (x *StartLiveResponse) GetWebrtcUrl() string {
	if x != nil {
		return x.WebrtcUrl
	}
	return ""
}

// ========== 结束直播 ==========
type StopLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        uint64                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLiveRequest) Reset() {
	*x = StopLiveRequest{}
	mi := &file_proto_live_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLiveRequest) ProtoMessage() {}

func (x *StopLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLiveRequest.ProtoReflect.Descriptor instead.
func (*StopLiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{5}
}

func (x *StopLiveRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StopLiveRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type StopLiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLiveResponse) Reset() {
	*x = StopLiveResponse{}
	mi := &file_proto_live_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLiveResponse) ProtoMessage() {}

func (x *StopLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLiveResponse.ProtoReflect.Descriptor instead.
func (*StopLiveResponse) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{6}
}

func (x *StopLiveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StopLiveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ========== 获取房间信息 ==========
type GetRoomInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoRequest) Reset() {
	*x = GetRoomInfoRequest{}
	mi := &file_proto_live_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoRequest) ProtoMessage() {}

func (x *GetRoomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRoomInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomInfoRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type GetRoomInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Room          *LiveRoom              `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoResponse) Reset() {
	*x = GetRoomInfoResponse{}
	mi := &file_proto_live_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoResponse) ProtoMessage() {}

func (x *GetRoomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRoomInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoomInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRoomInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRoomInfoResponse) GetRoom() *LiveRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

// ========== 进入直播间 ==========
type EnterRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        uint64                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterRoomRequest) Reset() {
	*x = EnterRoomRequest{}
	mi := &file_proto_live_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoomRequest) ProtoMessage() {}

func (x *EnterRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoomRequest.ProtoReflect.Descriptor instead.
func (*EnterRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{9}
}

func (x *EnterRoomRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EnterRoomRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type EnterRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PlayUrl       string                 `protobuf:"bytes,3,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,4,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterRoomResponse) Reset() {
	*x = EnterRoomResponse{}
	mi := &file_proto_live_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoomResponse) ProtoMessage() {}

func (x *EnterRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoomResponse.ProtoReflect.Descriptor instead.
func (*EnterRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{10}
}

func (x *EnterRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EnterRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnterRoomResponse) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *EnterRoomResponse) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

// ========== 离开直播间 ==========
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        uint64                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_proto_live_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveRoomRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LeaveRoomRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_proto_live_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{12}
}

func (x *LeaveRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LeaveRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ========== 获取直播列表 ==========
type GetLiveListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveListRequest) Reset() {
	*x = GetLiveListRequest{}
	mi := &file_proto_live_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveListRequest) ProtoMessage() {}

func (x *GetLiveListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveListRequest.ProtoReflect.Descriptor instead.
func (*GetLiveListRequest) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{13}
}

func (x *GetLiveListRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetLiveListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLiveListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetLiveListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Rooms         []*LiveRoom            `protobuf:"bytes,3,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveListResponse) Reset() {
	*x = GetLiveListResponse{}
	mi := &file_proto_live_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveListResponse) ProtoMessage() {}

func (x *GetLiveListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveListResponse.ProtoReflect.Descriptor instead.
func (*GetLiveListResponse) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{14}
}

func (x *GetLiveListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetLiveListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLiveListResponse) GetRooms() []*LiveRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetLiveListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ========== 数据模型 ==========
type LiveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // offline, streaming, banned
	CoverUrl      string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	StreamKey     string                 `protobuf:"bytes,7,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	PlayUrl       string                 `protobuf:"bytes,8,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,9,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	StartedAt     int64                  `protobuf:"varint,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       int64                  `protobuf:"varint,11,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveRoom) Reset() {
	*x = LiveRoom{}
	mi := &file_proto_live_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveRoom) ProtoMessage() {}

func (x *LiveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_live_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveRoom.ProtoReflect.Descriptor instead.
func (*LiveRoom) Descriptor() ([]byte, []int) {
	return file_proto_live_proto_rawDescGZIP(), []int{15}
}

func (x *LiveRoom) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LiveRoom) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LiveRoom) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LiveRoom) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *LiveRoom) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LiveRoom) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *LiveRoom) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *LiveRoom) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *LiveRoom) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *LiveRoom) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *LiveRoom) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *LiveRoom) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *LiveRoom) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_proto_live_proto protoreflect.FileDescriptor

const file_proto_live_proto_rawDesc = "" +
	"\n" +
	"\x10proto/live.proto\x12\x06livepb\"<\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\x11CreateRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\"\x95\x01\n" +
	"\x12CreateRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\x04R\x06roomId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x04 \x01(\tR\tstreamKey\x12\x19\n" +
	"\bpush_url\x18\x05 \x01(\tR\apushUrl\"z\n" +
	"\x10StartLiveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\"\x87\x02\n" +
	"\x11StartLiveResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\x04R\x06roomId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x04 \x01(\tR\tstreamKey\x12\x19\n" +
	"\bpush_url\x18\x05 \x01(\tR\apushUrl\x12\x19\n" +
	"\bplay_url\x18\x06 \x01(\tR\aplayUrl\x12\x1e\n" +
	"\vis_new_room\x18\a \x01(\bR\tisNewRoom\x12\x17\n" +
	"\aflv_url\x18\b \x01(\tR\x06flvUrl\x12\x1d\n" +
	"\n" +
	"webrtc_url\x18\t \x01(\tR\twebrtcUrl\"C\n" +
	"\x0fStopLiveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x04R\x06roomId\"@\n" +
	"\x10StopLiveResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12GetRoomInfoRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\"i\n" +
	"\x13GetRoomInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04room\x18\x03 \x01(\v2\x10.livepb.LiveRoomR\x04room\"D\n" +
	"\x10EnterRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x04R\x06roomId\"\x7f\n" +
	"\x11EnterRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bplay_url\x18\x03 \x01(\tR\aplayUrl\x12!\n" +
	"\fonline_count\x18\x04 \x01(\x05R\vonlineCount\"D\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x04R\x06roomId\"A\n" +
	"\x11LeaveRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"a\n" +
	"\x12GetLiveListRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x81\x01\n" +
	"\x13GetLiveListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x05rooms\x18\x03 \x03(\v2\x10.livepb.LiveRoomR\x05rooms\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\xef\x02\n" +
	"\bLiveRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x1d\n" +
	"\n" +
	"stream_key\x18\a \x01(\tR\tstreamKey\x12\x19\n" +
	"\bplay_url\x18\b \x01(\tR\aplayUrl\x12!\n" +
	"\fonline_count\x18\t \x01(\x05R\vonlineCount\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\v \x01(\x03R\aendedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt2\xe7\x03\n" +
	"\vLiveService\x12C\n" +
	"\n" +
	"CreateRoom\x12\x19.livepb.CreateRoomRequest\x1a\x1a.livepb.CreateRoomResponse\x12@\n" +
	"\tStartLive\x12\x18.livepb.StartLiveRequest\x1a\x19.livepb.StartLiveResponse\x12=\n" +
	"\bStopLive\x12\x17.livepb.StopLiveRequest\x1a\x18.livepb.StopLiveResponse\x12F\n" +
	"\vGetRoomInfo\x12\x1a.livepb.GetRoomInfoRequest\x1a\x1b.livepb.GetRoomInfoResponse\x12@\n" +
	"\tEnterRoom\x12\x18.livepb.EnterRoomRequest\x1a\x19.livepb.EnterRoomResponse\x12@\n" +
	"\tLeaveRoom\x12\x18.livepb.LeaveRoomRequest\x1a\x19.livepb.LeaveRoomResponse\x12F\n" +
	"\vGetLiveList\x12\x1a.livepb.GetLiveListRequest\x1a\x1b.livepb.GetLiveListResponseB0Z.github.com/vision_world/live_service/proto_genb\x06proto3"

var (
	file_proto_live_proto_rawDescOnce sync.Once
	file_proto_live_proto_rawDescData []byte
)

func file_proto_live_proto_rawDescGZIP() []byte {
	file_proto_live_proto_rawDescOnce.Do(func() {
		file_proto_live_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_live_proto_rawDesc), len(file_proto_live_proto_rawDesc)))
	})
	return file_proto_live_proto_rawDescData
}

var file_proto_live_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_live_proto_goTypes = []any{
	(*BaseResponse)(nil),        // 0: livepb.BaseResponse
	(*CreateRoomRequest)(nil),   // 1: livepb.CreateRoomRequest
	(*CreateRoomResponse)(nil),  // 2: livepb.CreateRoomResponse
	(*StartLiveRequest)(nil),    // 3: livepb.StartLiveRequest
	(*StartLiveResponse)(nil),   // 4: livepb.StartLiveResponse
	(*StopLiveRequest)(nil),     // 5: livepb.StopLiveRequest
	(*StopLiveResponse)(nil),    // 6: livepb.StopLiveResponse
	(*GetRoomInfoRequest)(nil),  // 7: livepb.GetRoomInfoRequest
	(*GetRoomInfoResponse)(nil), // 8: livepb.GetRoomInfoResponse
	(*EnterRoomRequest)(nil),    // 9: livepb.EnterRoomRequest
	(*EnterRoomResponse)(nil),   // 10: livepb.EnterRoomResponse
	(*LeaveRoomRequest)(nil),    // 11: livepb.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),   // 12: livepb.LeaveRoomResponse
	(*GetLiveListRequest)(nil),  // 13: livepb.GetLiveListRequest
	(*GetLiveListResponse)(nil), // 14: livepb.GetLiveListResponse
	(*LiveRoom)(nil),            // 15: livepb.LiveRoom
}
var file_proto_live_proto_depIdxs = []int32{
	15, // 0: livepb.GetRoomInfoResponse.room:type_name -> livepb.LiveRoom
	15, // 1: livepb.GetLiveListResponse.rooms:type_name -> livepb.LiveRoom
	1,  // 2: livepb.LiveService.CreateRoom:input_type -> livepb.CreateRoomRequest
	3,  // 3: livepb.LiveService.StartLive:input_type -> livepb.StartLiveRequest
	5,  // 4: livepb.LiveService.StopLive:input_type -> livepb.StopLiveRequest
	7,  // 5: livepb.LiveService.GetRoomInfo:input_type -> livepb.GetRoomInfoRequest
	9,  // 6: livepb.LiveService.EnterRoom:input_type -> livepb.EnterRoomRequest
	11, // 7: livepb.LiveService.LeaveRoom:input_type -> livepb.LeaveRoomRequest
	13, // 8: livepb.LiveService.GetLiveList:input_type -> livepb.GetLiveListRequest
	2,  // 9: livepb.LiveService.CreateRoom:output_type -> livepb.CreateRoomResponse
	4,  // 10: livepb.LiveService.StartLive:output_type -> livepb.StartLiveResponse
	6,  // 11: livepb.LiveService.StopLive:output_type -> livepb.StopLiveResponse
	8,  // 12: livepb.LiveService.GetRoomInfo:output_type -> livepb.GetRoomInfoResponse
	10, // 13: livepb.LiveService.EnterRoom:output_type -> livepb.EnterRoomResponse
	12, // 14: livepb.LiveService.LeaveRoom:output_type -> livepb.LeaveRoomResponse
	14, // 15: livepb.LiveService.GetLiveList:output_type -> livepb.GetLiveListResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_live_proto_init() }
func file_proto_live_proto_init() {
	if File_proto_live_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_live_proto_rawDesc), len(file_proto_live_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_live_proto_goTypes,
		DependencyIndexes: file_proto_live_proto_depIdxs,
		MessageInfos:      file_proto_live_proto_msgTypes,
	}.Build()
	File_proto_live_proto = out.File
	file_proto_live_proto_goTypes = nil
	file_proto_live_proto_depIdxs = nil
}
