// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.1
// source: audit.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 审核内容类型
type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED ContentType = 0
	ContentType_CONTENT_TYPE_VIDEO       ContentType = 1 // 视频
	ContentType_CONTENT_TYPE_IMAGE       ContentType = 2 // 图片
	ContentType_CONTENT_TYPE_TEXT        ContentType = 3 // 文本
	ContentType_CONTENT_TYPE_AUDIO       ContentType = 4 // 音频
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_VIDEO",
		2: "CONTENT_TYPE_IMAGE",
		3: "CONTENT_TYPE_TEXT",
		4: "CONTENT_TYPE_AUDIO",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED": 0,
		"CONTENT_TYPE_VIDEO":       1,
		"CONTENT_TYPE_IMAGE":       2,
		"CONTENT_TYPE_TEXT":        3,
		"CONTENT_TYPE_AUDIO":       4,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_audit_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_audit_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

// 审核状态
type AuditStatus int32

const (
	AuditStatus_AUDIT_STATUS_UNSPECIFIED  AuditStatus = 0
	AuditStatus_AUDIT_STATUS_PENDING      AuditStatus = 1 // 待审核
	AuditStatus_AUDIT_STATUS_UNDER_REVIEW AuditStatus = 2 // 审核中
	AuditStatus_AUDIT_STATUS_PASSED       AuditStatus = 3 // 审核通过
	AuditStatus_AUDIT_STATUS_REJECTED     AuditStatus = 4 // 审核拒绝
	AuditStatus_AUDIT_STATUS_FAILED       AuditStatus = 5 // 审核失败
)

// Enum value maps for AuditStatus.
var (
	AuditStatus_name = map[int32]string{
		0: "AUDIT_STATUS_UNSPECIFIED",
		1: "AUDIT_STATUS_PENDING",
		2: "AUDIT_STATUS_UNDER_REVIEW",
		3: "AUDIT_STATUS_PASSED",
		4: "AUDIT_STATUS_REJECTED",
		5: "AUDIT_STATUS_FAILED",
	}
	AuditStatus_value = map[string]int32{
		"AUDIT_STATUS_UNSPECIFIED":  0,
		"AUDIT_STATUS_PENDING":      1,
		"AUDIT_STATUS_UNDER_REVIEW": 2,
		"AUDIT_STATUS_PASSED":       3,
		"AUDIT_STATUS_REJECTED":     4,
		"AUDIT_STATUS_FAILED":       5,
	}
)

func (x AuditStatus) Enum() *AuditStatus {
	p := new(AuditStatus)
	*p = x
	return p
}

func (x AuditStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_audit_proto_enumTypes[1].Descriptor()
}

func (AuditStatus) Type() protoreflect.EnumType {
	return &file_audit_proto_enumTypes[1]
}

func (x AuditStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditStatus.Descriptor instead.
func (AuditStatus) EnumDescriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

// 提交审核请求
type SubmitContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`                                  // 内容ID
	ContentType   ContentType            `protobuf:"varint,2,opt,name=content_type,json=contentType,proto3,enum=audit.v1.ContentType" json:"content_type,omitempty"` // 内容类型
	UploaderId    string                 `protobuf:"bytes,3,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`                               // 上传者ID
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                                           // 标题
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                                       // 内容描述
	CreateTime    string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                               // 创建时间 (RFC3339格式)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitContentRequest) Reset() {
	*x = SubmitContentRequest{}
	mi := &file_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitContentRequest) ProtoMessage() {}

func (x *SubmitContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitContentRequest.ProtoReflect.Descriptor instead.
func (*SubmitContentRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *SubmitContentRequest) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *SubmitContentRequest) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *SubmitContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubmitContentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubmitContentRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 提交审核响应
type SubmitContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`           // 审核ID
	Status        AuditStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=audit.v1.AuditStatus" json:"status,omitempty"` // 审核状态
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitContentResponse) Reset() {
	*x = SubmitContentResponse{}
	mi := &file_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitContentResponse) ProtoMessage() {}

func (x *SubmitContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitContentResponse.ProtoReflect.Descriptor instead.
func (*SubmitContentResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitContentResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *SubmitContentResponse) GetStatus() AuditStatus {
	if x != nil {
		return x.Status
	}
	return AuditStatus_AUDIT_STATUS_UNSPECIFIED
}

func (x *SubmitContentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取审核信息请求
type GetAuditInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"` // 审核ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditInfoRequest) Reset() {
	*x = GetAuditInfoRequest{}
	mi := &file_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditInfoRequest) ProtoMessage() {}

func (x *GetAuditInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAuditInfoRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuditInfoRequest) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

// 获取审核信息响应
type GetAuditInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`                                        // 审核ID
	ContentId     string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`                                  // 内容ID
	ContentType   ContentType            `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=audit.v1.ContentType" json:"content_type,omitempty"` // 内容类型
	UploaderId    string                 `protobuf:"bytes,4,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`                               // 上传者ID
	Status        AuditStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=audit.v1.AuditStatus" json:"status,omitempty"`                              // 审核状态
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                                         // 审核原因
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                               // 创建时间
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                               // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditInfoResponse) Reset() {
	*x = GetAuditInfoResponse{}
	mi := &file_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditInfoResponse) ProtoMessage() {}

func (x *GetAuditInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAuditInfoResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuditInfoResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *GetAuditInfoResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetAuditInfoResponse) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *GetAuditInfoResponse) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *GetAuditInfoResponse) GetStatus() AuditStatus {
	if x != nil {
		return x.Status
	}
	return AuditStatus_AUDIT_STATUS_UNSPECIFIED
}

func (x *GetAuditInfoResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetAuditInfoResponse) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GetAuditInfoResponse) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// 更新审核状态请求
type UpdateAuditStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`           // 审核ID
	Status        AuditStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=audit.v1.AuditStatus" json:"status,omitempty"` // 新的审核状态
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                            // 审核原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuditStatusRequest) Reset() {
	*x = UpdateAuditStatusRequest{}
	mi := &file_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuditStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuditStatusRequest) ProtoMessage() {}

func (x *UpdateAuditStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuditStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAuditStatusRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAuditStatusRequest) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *UpdateAuditStatusRequest) GetStatus() AuditStatus {
	if x != nil {
		return x.Status
	}
	return AuditStatus_AUDIT_STATUS_UNSPECIFIED
}

func (x *UpdateAuditStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 更新审核状态响应
type UpdateAuditStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuditStatusResponse) Reset() {
	*x = UpdateAuditStatusResponse{}
	mi := &file_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuditStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuditStatusResponse) ProtoMessage() {}

func (x *UpdateAuditStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuditStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateAuditStatusResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAuditStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAuditStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 审核列表请求
type GetAuditListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploaderId    string                 `protobuf:"bytes,1,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`                               // 上传者ID（可选）
	ContentType   ContentType            `protobuf:"varint,2,opt,name=content_type,json=contentType,proto3,enum=audit.v1.ContentType" json:"content_type,omitempty"` // 内容类型（可选）
	Status        AuditStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=audit.v1.AuditStatus" json:"status,omitempty"`                              // 审核状态（可选）
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                                                            // 页码
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                                    // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditListRequest) Reset() {
	*x = GetAuditListRequest{}
	mi := &file_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditListRequest) ProtoMessage() {}

func (x *GetAuditListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditListRequest.ProtoReflect.Descriptor instead.
func (*GetAuditListRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuditListRequest) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *GetAuditListRequest) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *GetAuditListRequest) GetStatus() AuditStatus {
	if x != nil {
		return x.Status
	}
	return AuditStatus_AUDIT_STATUS_UNSPECIFIED
}

func (x *GetAuditListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAuditListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 审核列表响应
type GetAuditListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Audits        []*GetAuditInfoResponse `protobuf:"bytes,1,rep,name=audits,proto3" json:"audits,omitempty"`                      // 审核列表
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditListResponse) Reset() {
	*x = GetAuditListResponse{}
	mi := &file_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditListResponse) ProtoMessage() {}

func (x *GetAuditListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditListResponse.ProtoReflect.Descriptor instead.
func (*GetAuditListResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuditListResponse) GetAudits() []*GetAuditInfoResponse {
	if x != nil {
		return x.Audits
	}
	return nil
}

func (x *GetAuditListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAuditListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAuditListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_audit_proto protoreflect.FileDescriptor

const file_audit_proto_rawDesc = "" +
	"\n" +
	"\vaudit.proto\x12\baudit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x01\n" +
	"\x14SubmitContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x128\n" +
	"\fcontent_type\x18\x02 \x01(\x0e2\x15.audit.v1.ContentTypeR\vcontentType\x12\x1f\n" +
	"\vuploader_id\x18\x03 \x01(\tR\n" +
	"uploaderId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\"{\n" +
	"\x15SubmitContentResponse\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.audit.v1.AuditStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"0\n" +
	"\x13GetAuditInfoRequest\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\"\xec\x02\n" +
	"\x14GetAuditInfoResponse\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x128\n" +
	"\fcontent_type\x18\x03 \x01(\x0e2\x15.audit.v1.ContentTypeR\vcontentType\x12\x1f\n" +
	"\vuploader_id\x18\x04 \x01(\tR\n" +
	"uploaderId\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.audit.v1.AuditStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12;\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"|\n" +
	"\x18UpdateAuditStatusRequest\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.audit.v1.AuditStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"O\n" +
	"\x19UpdateAuditStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd0\x01\n" +
	"\x13GetAuditListRequest\x12\x1f\n" +
	"\vuploader_id\x18\x01 \x01(\tR\n" +
	"uploaderId\x128\n" +
	"\fcontent_type\x18\x02 \x01(\x0e2\x15.audit.v1.ContentTypeR\vcontentType\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.audit.v1.AuditStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\x95\x01\n" +
	"\x14GetAuditListResponse\x126\n" +
	"\x06audits\x18\x01 \x03(\v2\x1e.audit.v1.GetAuditInfoResponseR\x06audits\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize*\x8a\x01\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTENT_TYPE_VIDEO\x10\x01\x12\x16\n" +
	"\x12CONTENT_TYPE_IMAGE\x10\x02\x12\x15\n" +
	"\x11CONTENT_TYPE_TEXT\x10\x03\x12\x16\n" +
	"\x12CONTENT_TYPE_AUDIO\x10\x04*\xb1\x01\n" +
	"\vAuditStatus\x12\x1c\n" +
	"\x18AUDIT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUDIT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19AUDIT_STATUS_UNDER_REVIEW\x10\x02\x12\x17\n" +
	"\x13AUDIT_STATUS_PASSED\x10\x03\x12\x19\n" +
	"\x15AUDIT_STATUS_REJECTED\x10\x04\x12\x17\n" +
	"\x13AUDIT_STATUS_FAILED\x10\x052\xdc\x02\n" +
	"\fAuditService\x12P\n" +
	"\rSubmitContent\x12\x1e.audit.v1.SubmitContentRequest\x1a\x1f.audit.v1.SubmitContentResponse\x12M\n" +
	"\fGetAuditInfo\x12\x1d.audit.v1.GetAuditInfoRequest\x1a\x1e.audit.v1.GetAuditInfoResponse\x12\\\n" +
	"\x11UpdateAuditStatus\x12\".audit.v1.UpdateAuditStatusRequest\x1a#.audit.v1.UpdateAuditStatusResponse\x12M\n" +
	"\fGetAuditList\x12\x1d.audit.v1.GetAuditListRequest\x1a\x1e.audit.v1.GetAuditListResponseB@Z>github.com/vision_world/audit_service/proto/proto_gen/audit/v1b\x06proto3"

var (
	file_audit_proto_rawDescOnce sync.Once
	file_audit_proto_rawDescData []byte
)

func file_audit_proto_rawDescGZIP() []byte {
	file_audit_proto_rawDescOnce.Do(func() {
		file_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)))
	})
	return file_audit_proto_rawDescData
}

var file_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_audit_proto_goTypes = []any{
	(ContentType)(0),                  // 0: audit.v1.ContentType
	(AuditStatus)(0),                  // 1: audit.v1.AuditStatus
	(*SubmitContentRequest)(nil),      // 2: audit.v1.SubmitContentRequest
	(*SubmitContentResponse)(nil),     // 3: audit.v1.SubmitContentResponse
	(*GetAuditInfoRequest)(nil),       // 4: audit.v1.GetAuditInfoRequest
	(*GetAuditInfoResponse)(nil),      // 5: audit.v1.GetAuditInfoResponse
	(*UpdateAuditStatusRequest)(nil),  // 6: audit.v1.UpdateAuditStatusRequest
	(*UpdateAuditStatusResponse)(nil), // 7: audit.v1.UpdateAuditStatusResponse
	(*GetAuditListRequest)(nil),       // 8: audit.v1.GetAuditListRequest
	(*GetAuditListResponse)(nil),      // 9: audit.v1.GetAuditListResponse
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_audit_proto_depIdxs = []int32{
	0,  // 0: audit.v1.SubmitContentRequest.content_type:type_name -> audit.v1.ContentType
	1,  // 1: audit.v1.SubmitContentResponse.status:type_name -> audit.v1.AuditStatus
	0,  // 2: audit.v1.GetAuditInfoResponse.content_type:type_name -> audit.v1.ContentType
	1,  // 3: audit.v1.GetAuditInfoResponse.status:type_name -> audit.v1.AuditStatus
	10, // 4: audit.v1.GetAuditInfoResponse.create_time:type_name -> google.protobuf.Timestamp
	10, // 5: audit.v1.GetAuditInfoResponse.update_time:type_name -> google.protobuf.Timestamp
	1,  // 6: audit.v1.UpdateAuditStatusRequest.status:type_name -> audit.v1.AuditStatus
	0,  // 7: audit.v1.GetAuditListRequest.content_type:type_name -> audit.v1.ContentType
	1,  // 8: audit.v1.GetAuditListRequest.status:type_name -> audit.v1.AuditStatus
	5,  // 9: audit.v1.GetAuditListResponse.audits:type_name -> audit.v1.GetAuditInfoResponse
	2,  // 10: audit.v1.AuditService.SubmitContent:input_type -> audit.v1.SubmitContentRequest
	4,  // 11: audit.v1.AuditService.GetAuditInfo:input_type -> audit.v1.GetAuditInfoRequest
	6,  // 12: audit.v1.AuditService.UpdateAuditStatus:input_type -> audit.v1.UpdateAuditStatusRequest
	8,  // 13: audit.v1.AuditService.GetAuditList:input_type -> audit.v1.GetAuditListRequest
	3,  // 14: audit.v1.AuditService.SubmitContent:output_type -> audit.v1.SubmitContentResponse
	5,  // 15: audit.v1.AuditService.GetAuditInfo:output_type -> audit.v1.GetAuditInfoResponse
	7,  // 16: audit.v1.AuditService.UpdateAuditStatus:output_type -> audit.v1.UpdateAuditStatusResponse
	9,  // 17: audit.v1.AuditService.GetAuditList:output_type -> audit.v1.GetAuditListResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_audit_proto_init() }
func file_audit_proto_init() {
	if File_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_proto_goTypes,
		DependencyIndexes: file_audit_proto_depIdxs,
		EnumInfos:         file_audit_proto_enumTypes,
		MessageInfos:      file_audit_proto_msgTypes,
	}.Build()
	File_audit_proto = out.File
	file_audit_proto_goTypes = nil
	file_audit_proto_depIdxs = nil
}
