server:
  host: "0.0.0.0"
  port: 3000
  mode: "debug"

etcd:
  endpoints:
    - "localhost:2379"

logger:
  level: "info"
  format: "json"

#minio:
#  endpoint: "localhost:9000"
#  access_key_id: "minioadmin"
#  secret_access_key: "minioadmin"
#  use_ssl: false
#  bucket_name: "videos"
#  location: "us-east-1"
