# 用户服务配置
server:
  name: "user-service"
  host: "0.0.0.0"
  port: 8081
  mode: "debug"  # debug, release, test

# gRPC配置
grpc:
  port: 9001
  max_connection_idle: 300
  max_connection_age: 300
  max_connection_age_grace: 5
  keepalive_time: 30
  keepalive_timeout: 20

# 数据库配置
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  database: "vision_world_user"
  username: "root"
  password: ""
  charset: "utf8mb4"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600
  log_level: "info"  # silent, error, warn, info

# Redis配置
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3

# JWT配置
jwt:
  secret: "vision-world-jwt-secret-key-2024"
  access_token_expire: 7200  # 2小时
  refresh_token_expire: 604800  # 7天
  issuer: "vision-world"

# 验证码配置
sms:
  expire_time: 300  # 5分钟
  max_send_per_day: 10  # 每天最多发送次数
  cool_down_time: 60  # 冷却时间60秒

# 日志配置
log:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, file
  file_path: "logs/user-service.log"
  max_size: 100  # MB
  max_backups: 5
  max_age: 30  # days
  compress: true

# 监控配置
metrics:
  enabled: true
  port: 9091
  path: "/metrics"

# 链路追踪
tracing:
  enabled: true
  jaeger_endpoint: "http://localhost:14268/api/traces"
  sample_rate: 1.0

# 限流配置
rate_limit:
  enabled: true
  requests_per_second: 100
  burst: 200

# 熔断配置
circuit_breaker:
  enabled: true
  failure_threshold: 5
  success_threshold: 2
  timeout: 30

# 健康检查
health:
  path: "/health"
  timeout: 5

# 外部服务配置
external_services:
  api_gateway:
    addr: "localhost:8080"
    timeout: 5
  
  sms_service:
    provider: "aliyun"  # aliyun, tencent, huawei
    access_key: ""
    secret_key: ""
    sign_name: "VisionWorld"
    template_code: "SMS_123456789"

# 安全配置
security:
  bcrypt_cost: 10
  max_login_attempts: 5
  lockout_duration: 900  # 15分钟
  password_min_length: 8
  password_require_uppercase: true
  password_require_lowercase: true
  password_require_digit: true
  password_require_special: true