// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.1
// source: video.proto

package proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint32                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频id
	ActorId       uint32                 `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // 发送请求的用户的id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRequest) Reset() {
	*x = VideoRequest{}
	mi := &file_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRequest) ProtoMessage() {}

func (x *VideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRequest.ProtoReflect.Descriptor instead.
func (*VideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

func (x *VideoRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoRequest) GetActorId() uint32 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

type VideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	Video         *Video                 `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`                              // 视频信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	mi := &file_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{1}
}

func (x *VideoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *VideoResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *VideoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

// 上传视频请求
type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // 用户token
	VideoData     []byte                 `protobuf:"bytes,2,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"` // 视频文件二进制数据
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`    // 原始文件名
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                          // 视频标题
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`              // 视频描述
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`                    // 视频分类
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                            // 视频标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{2}
}

func (x *UploadVideoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UploadVideoRequest) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *UploadVideoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadVideoRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UploadVideoRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 上传视频响应
type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	VideoId       uint32                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`          // 上传的视频ID
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`        // 视频URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{3}
}

func (x *UploadVideoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UploadVideoResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *UploadVideoResponse) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *UploadVideoResponse) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

// 获取视频信息请求
type GetVideoInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint32                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoInfoRequest) Reset() {
	*x = GetVideoInfoRequest{}
	mi := &file_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoRequest) ProtoMessage() {}

func (x *GetVideoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoInfoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoInfoRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

// 获取视频信息响应
type GetVideoInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	Video         *Video                 `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`                              // 视频信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoInfoResponse) Reset() {
	*x = GetVideoInfoResponse{}
	mi := &file_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInfoResponse) ProtoMessage() {}

func (x *GetVideoInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInfoResponse.ProtoReflect.Descriptor instead.
func (*GetVideoInfoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoInfoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetVideoInfoResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetVideoInfoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

// 获取用户视频列表请求
type GetVideosByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // 返回数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosByUserRequest) Reset() {
	*x = GetVideosByUserRequest{}
	mi := &file_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosByUserRequest) ProtoMessage() {}

func (x *GetVideosByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosByUserRequest.ProtoReflect.Descriptor instead.
func (*GetVideosByUserRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideosByUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetVideosByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取用户视频列表响应
type GetVideosByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	Videos        []*Video               `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`                            // 视频列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosByUserResponse) Reset() {
	*x = GetVideosByUserResponse{}
	mi := &file_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosByUserResponse) ProtoMessage() {}

func (x *GetVideosByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosByUserResponse.ProtoReflect.Descriptor instead.
func (*GetVideosByUserResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideosByUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetVideosByUserResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetVideosByUserResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 创建视频请求
type CreateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                       // 视频标题
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`           // 视频描述
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"` // 视频URL
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"` // 封面URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVideoRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVideoRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *CreateVideoRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

// 创建视频响应
type CreateVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	VideoId       uint32                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`          // 视频ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoResponse) Reset() {
	*x = CreateVideoResponse{}
	mi := &file_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoResponse) ProtoMessage() {}

func (x *CreateVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoResponse.ProtoReflect.Descriptor instead.
func (*CreateVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVideoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateVideoResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CreateVideoResponse) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

// 更新视频请求
type UpdateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint32                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                     // 视频标题
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`         // 视频描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoRequest) Reset() {
	*x = UpdateVideoRequest{}
	mi := &file_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoRequest) ProtoMessage() {}

func (x *UpdateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVideoRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *UpdateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 更新视频响应
type UpdateVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoResponse) Reset() {
	*x = UpdateVideoResponse{}
	mi := &file_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoResponse) ProtoMessage() {}

func (x *UpdateVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateVideoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateVideoResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// 删除视频请求
type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint32                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频ID
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVideoRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *DeleteVideoRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 删除视频响应
type DeleteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResponse) Reset() {
	*x = DeleteVideoResponse{}
	mi := &file_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResponse) ProtoMessage() {}

func (x *DeleteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteVideoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteVideoResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// 获取推荐视频请求
type GetRecommendedVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 返回数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedVideosRequest) Reset() {
	*x = GetRecommendedVideosRequest{}
	mi := &file_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedVideosRequest) ProtoMessage() {}

func (x *GetRecommendedVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedVideosRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendedVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{14}
}

func (x *GetRecommendedVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取推荐视频响应
type GetRecommendedVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	Videos        []*Video               `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`                            // 视频列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedVideosResponse) Reset() {
	*x = GetRecommendedVideosResponse{}
	mi := &file_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedVideosResponse) ProtoMessage() {}

func (x *GetRecommendedVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedVideosResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendedVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{15}
}

func (x *GetRecommendedVideosResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetRecommendedVideosResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetRecommendedVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 获取个性化视频请求
type GetPersonalizedVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // 返回数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalizedVideosRequest) Reset() {
	*x = GetPersonalizedVideosRequest{}
	mi := &file_video_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalizedVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalizedVideosRequest) ProtoMessage() {}

func (x *GetPersonalizedVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalizedVideosRequest.ProtoReflect.Descriptor instead.
func (*GetPersonalizedVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{16}
}

func (x *GetPersonalizedVideosRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPersonalizedVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取个性化视频响应
type GetPersonalizedVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	Videos        []*Video               `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`                            // 视频列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalizedVideosResponse) Reset() {
	*x = GetPersonalizedVideosResponse{}
	mi := &file_video_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalizedVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalizedVideosResponse) ProtoMessage() {}

func (x *GetPersonalizedVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalizedVideosResponse.ProtoReflect.Descriptor instead.
func (*GetPersonalizedVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{17}
}

func (x *GetPersonalizedVideosResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetPersonalizedVideosResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetPersonalizedVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 获取关注用户视频请求
type GetFollowVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // 返回数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowVideosRequest) Reset() {
	*x = GetFollowVideosRequest{}
	mi := &file_video_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowVideosRequest) ProtoMessage() {}

func (x *GetFollowVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowVideosRequest.ProtoReflect.Descriptor instead.
func (*GetFollowVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{18}
}

func (x *GetFollowVideosRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取关注用户视频响应
type GetFollowVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	Videos        []*Video               `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`                            // 视频列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowVideosResponse) Reset() {
	*x = GetFollowVideosResponse{}
	mi := &file_video_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowVideosResponse) ProtoMessage() {}

func (x *GetFollowVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowVideosResponse.ProtoReflect.Descriptor instead.
func (*GetFollowVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{19}
}

func (x *GetFollowVideosResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetFollowVideosResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetFollowVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 获取热门视频请求
type GetHotVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // 返回数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotVideosRequest) Reset() {
	*x = GetHotVideosRequest{}
	mi := &file_video_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotVideosRequest) ProtoMessage() {}

func (x *GetHotVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotVideosRequest.ProtoReflect.Descriptor instead.
func (*GetHotVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{20}
}

func (x *GetHotVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取热门视频响应
type GetHotVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	Videos        []*Video               `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`                            // 视频列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotVideosResponse) Reset() {
	*x = GetHotVideosResponse{}
	mi := &file_video_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotVideosResponse) ProtoMessage() {}

func (x *GetHotVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotVideosResponse.ProtoReflect.Descriptor instead.
func (*GetHotVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{21}
}

func (x *GetHotVideosResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetHotVideosResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetHotVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 点赞视频请求
type LikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID
	VideoId       uint32                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频ID
	Action        int32                  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`                  // 操作类型：1-点赞，2-取消点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoRequest) Reset() {
	*x = LikeVideoRequest{}
	mi := &file_video_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoRequest) ProtoMessage() {}

func (x *LikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoRequest.ProtoReflect.Descriptor instead.
func (*LikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{22}
}

func (x *LikeVideoRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeVideoRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikeVideoRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 点赞视频响应
type LikeVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoResponse) Reset() {
	*x = LikeVideoResponse{}
	mi := &file_video_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoResponse) ProtoMessage() {}

func (x *LikeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoResponse.ProtoReflect.Descriptor instead.
func (*LikeVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{23}
}

func (x *LikeVideoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LikeVideoResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// 获取用户点赞视频请求
type GetUserLikedVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // 返回数量限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLikedVideosRequest) Reset() {
	*x = GetUserLikedVideosRequest{}
	mi := &file_video_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLikedVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikedVideosRequest) ProtoMessage() {}

func (x *GetUserLikedVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikedVideosRequest.ProtoReflect.Descriptor instead.
func (*GetUserLikedVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserLikedVideosRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserLikedVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 获取用户点赞视频响应
type GetUserLikedVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	Videos        []*Video               `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`                            // 视频列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLikedVideosResponse) Reset() {
	*x = GetUserLikedVideosResponse{}
	mi := &file_video_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLikedVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikedVideosResponse) ProtoMessage() {}

func (x *GetUserLikedVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikedVideosResponse.ProtoReflect.Descriptor instead.
func (*GetUserLikedVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserLikedVideosResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUserLikedVideosResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetUserLikedVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 分享视频请求
type ShareVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID
	VideoId       uint32                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareVideoRequest) Reset() {
	*x = ShareVideoRequest{}
	mi := &file_video_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareVideoRequest) ProtoMessage() {}

func (x *ShareVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareVideoRequest.ProtoReflect.Descriptor instead.
func (*ShareVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{26}
}

func (x *ShareVideoRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShareVideoRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

// 分享视频响应
type ShareVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareVideoResponse) Reset() {
	*x = ShareVideoResponse{}
	mi := &file_video_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareVideoResponse) ProtoMessage() {}

func (x *ShareVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareVideoResponse.ProtoReflect.Descriptor instead.
func (*ShareVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{27}
}

func (x *ShareVideoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ShareVideoResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// 评论请求
type CommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID
	VideoId       uint32                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` // 视频ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                 // 评论内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentRequest) Reset() {
	*x = CommentRequest{}
	mi := &file_video_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequest) ProtoMessage() {}

func (x *CommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequest.ProtoReflect.Descriptor instead.
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{28}
}

func (x *CommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 评论响应
type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	CommentId     uint32                 `protobuf:"varint,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`    // 评论ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_video_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{29}
}

func (x *CommentResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CommentResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CommentResponse) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

// 删除评论请求
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint32                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 评论ID
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_video_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteCommentRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteCommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 删除评论响应
type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_video_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteCommentResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteCommentResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 视频ID
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                    // 用户ID
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                     // 视频标题
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                         // 视频描述
	VideoUrl      string                 `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`               // 视频URL
	CoverUrl      string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`               // 封面URL
	CreateTime    int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`        // 创建时间戳
	UpdateTime    int64                  `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`        // 更新时间戳
	ViewCount     int32                  `protobuf:"varint,9,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`           // 播放次数
	LikeCount     int32                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞数
	CommentCount  int32                  `protobuf:"varint,11,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论数
	ShareCount    int32                  `protobuf:"varint,12,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`       // 分享数
	Category      string                 `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`                              // 视频分类
	Status        int32                  `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`                                 // 视频状态：0-正常，1-审核中，2-已下架
	Author        *User                  `protobuf:"bytes,15,opt,name=author,proto3" json:"author,omitempty"`                                  // 作者信息
	IsLiked       bool                   `protobuf:"varint,16,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`                // 当前用户是否已点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_video_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{32}
}

func (x *Video) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Video) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Video) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Video) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Video) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetShareCount() int32 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Video) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Video) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Video) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Video) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

var File_video_proto protoreflect.FileDescriptor

const file_video_proto_rawDesc = "" +
	"\n" +
	"\vvideo.proto\x12\trpc.video\x1a\n" +
	"user.proto\"D\n" +
	"\fVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\rR\avideoId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\rR\aactorId\"w\n" +
	"\rVideoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12&\n" +
	"\x05video\x18\x03 \x01(\v2\x10.rpc.video.VideoR\x05video\"\xce\x01\n" +
	"\x12UploadVideoRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"video_data\x18\x02 \x01(\fR\tvideoData\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\x8d\x01\n" +
	"\x13UploadVideoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\rR\avideoId\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\"0\n" +
	"\x13GetVideoInfoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\rR\avideoId\"~\n" +
	"\x14GetVideoInfoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12&\n" +
	"\x05video\x18\x03 \x01(\v2\x10.rpc.video.VideoR\x05video\"G\n" +
	"\x16GetVideosByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x17GetVideosByUserResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12(\n" +
	"\x06videos\x18\x03 \x03(\v2\x10.rpc.video.VideoR\x06videos\"\x9f\x01\n" +
	"\x12CreateVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\"p\n" +
	"\x13CreateVideoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\rR\avideoId\"g\n" +
	"\x12UpdateVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\rR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"U\n" +
	"\x13UpdateVideoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"H\n" +
	"\x12DeleteVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\rR\avideoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"U\n" +
	"\x13DeleteVideoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"3\n" +
	"\x1bGetRecommendedVideosRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x88\x01\n" +
	"\x1cGetRecommendedVideosResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12(\n" +
	"\x06videos\x18\x03 \x03(\v2\x10.rpc.video.VideoR\x06videos\"M\n" +
	"\x1cGetPersonalizedVideosRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x89\x01\n" +
	"\x1dGetPersonalizedVideosResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12(\n" +
	"\x06videos\x18\x03 \x03(\v2\x10.rpc.video.VideoR\x06videos\"G\n" +
	"\x16GetFollowVideosRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x17GetFollowVideosResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12(\n" +
	"\x06videos\x18\x03 \x03(\v2\x10.rpc.video.VideoR\x06videos\"+\n" +
	"\x13GetHotVideosRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x80\x01\n" +
	"\x14GetHotVideosResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12(\n" +
	"\x06videos\x18\x03 \x03(\v2\x10.rpc.video.VideoR\x06videos\"^\n" +
	"\x10LikeVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\rR\avideoId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\x05R\x06action\"S\n" +
	"\x11LikeVideoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"J\n" +
	"\x19GetUserLikedVideosRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x86\x01\n" +
	"\x1aGetUserLikedVideosResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12(\n" +
	"\x06videos\x18\x03 \x03(\v2\x10.rpc.video.VideoR\x06videos\"G\n" +
	"\x11ShareVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\rR\avideoId\"T\n" +
	"\x12ShareVideoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"^\n" +
	"\x0eCommentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\rR\avideoId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"p\n" +
	"\x0fCommentResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x03 \x01(\rR\tcommentId\"N\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\rR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"W\n" +
	"\x15DeleteCommentResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"\xdf\x03\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x05 \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\b \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"view_count\x18\t \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\v \x01(\x05R\fcommentCount\x12\x1f\n" +
	"\vshare_count\x18\f \x01(\x05R\n" +
	"shareCount\x12\x1a\n" +
	"\bcategory\x18\r \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\x12&\n" +
	"\x06author\x18\x0f \x01(\v2\x0e.rpc.user.UserR\x06author\x12\x19\n" +
	"\bis_liked\x18\x10 \x01(\bR\aisLiked2\xfd\t\n" +
	"\fVideoService\x12L\n" +
	"\vUploadVideo\x12\x1d.rpc.video.UploadVideoRequest\x1a\x1e.rpc.video.UploadVideoResponse\x12O\n" +
	"\fGetVideoInfo\x12\x1e.rpc.video.GetVideoInfoRequest\x1a\x1f.rpc.video.GetVideoInfoResponse\x12X\n" +
	"\x0fGetVideosByUser\x12!.rpc.video.GetVideosByUserRequest\x1a\".rpc.video.GetVideosByUserResponse\x12L\n" +
	"\vCreateVideo\x12\x1d.rpc.video.CreateVideoRequest\x1a\x1e.rpc.video.CreateVideoResponse\x12L\n" +
	"\vUpdateVideo\x12\x1d.rpc.video.UpdateVideoRequest\x1a\x1e.rpc.video.UpdateVideoResponse\x12L\n" +
	"\vDeleteVideo\x12\x1d.rpc.video.DeleteVideoRequest\x1a\x1e.rpc.video.DeleteVideoResponse\x12g\n" +
	"\x14GetRecommendedVideos\x12&.rpc.video.GetRecommendedVideosRequest\x1a'.rpc.video.GetRecommendedVideosResponse\x12j\n" +
	"\x15GetPersonalizedVideos\x12'.rpc.video.GetPersonalizedVideosRequest\x1a(.rpc.video.GetPersonalizedVideosResponse\x12X\n" +
	"\x0fGetFollowVideos\x12!.rpc.video.GetFollowVideosRequest\x1a\".rpc.video.GetFollowVideosResponse\x12O\n" +
	"\fGetHotVideos\x12\x1e.rpc.video.GetHotVideosRequest\x1a\x1f.rpc.video.GetHotVideosResponse\x12F\n" +
	"\tLikeVideo\x12\x1b.rpc.video.LikeVideoRequest\x1a\x1c.rpc.video.LikeVideoResponse\x12a\n" +
	"\x12GetUserLikedVideos\x12$.rpc.video.GetUserLikedVideosRequest\x1a%.rpc.video.GetUserLikedVideosResponse\x12I\n" +
	"\n" +
	"ShareVideo\x12\x1c.rpc.video.ShareVideoRequest\x1a\x1d.rpc.video.ShareVideoResponse\x12@\n" +
	"\aComment\x12\x19.rpc.video.CommentRequest\x1a\x1a.rpc.video.CommentResponse\x12R\n" +
	"\rDeleteComment\x12\x1f.rpc.video.DeleteCommentRequest\x1a .rpc.video.DeleteCommentResponseB\x1dZ\x1bapi_gateway/proto/proto_genb\x06proto3"

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData []byte
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)))
	})
	return file_video_proto_rawDescData
}

var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_video_proto_goTypes = []any{
	(*VideoRequest)(nil),                  // 0: rpc.video.VideoRequest
	(*VideoResponse)(nil),                 // 1: rpc.video.VideoResponse
	(*UploadVideoRequest)(nil),            // 2: rpc.video.UploadVideoRequest
	(*UploadVideoResponse)(nil),           // 3: rpc.video.UploadVideoResponse
	(*GetVideoInfoRequest)(nil),           // 4: rpc.video.GetVideoInfoRequest
	(*GetVideoInfoResponse)(nil),          // 5: rpc.video.GetVideoInfoResponse
	(*GetVideosByUserRequest)(nil),        // 6: rpc.video.GetVideosByUserRequest
	(*GetVideosByUserResponse)(nil),       // 7: rpc.video.GetVideosByUserResponse
	(*CreateVideoRequest)(nil),            // 8: rpc.video.CreateVideoRequest
	(*CreateVideoResponse)(nil),           // 9: rpc.video.CreateVideoResponse
	(*UpdateVideoRequest)(nil),            // 10: rpc.video.UpdateVideoRequest
	(*UpdateVideoResponse)(nil),           // 11: rpc.video.UpdateVideoResponse
	(*DeleteVideoRequest)(nil),            // 12: rpc.video.DeleteVideoRequest
	(*DeleteVideoResponse)(nil),           // 13: rpc.video.DeleteVideoResponse
	(*GetRecommendedVideosRequest)(nil),   // 14: rpc.video.GetRecommendedVideosRequest
	(*GetRecommendedVideosResponse)(nil),  // 15: rpc.video.GetRecommendedVideosResponse
	(*GetPersonalizedVideosRequest)(nil),  // 16: rpc.video.GetPersonalizedVideosRequest
	(*GetPersonalizedVideosResponse)(nil), // 17: rpc.video.GetPersonalizedVideosResponse
	(*GetFollowVideosRequest)(nil),        // 18: rpc.video.GetFollowVideosRequest
	(*GetFollowVideosResponse)(nil),       // 19: rpc.video.GetFollowVideosResponse
	(*GetHotVideosRequest)(nil),           // 20: rpc.video.GetHotVideosRequest
	(*GetHotVideosResponse)(nil),          // 21: rpc.video.GetHotVideosResponse
	(*LikeVideoRequest)(nil),              // 22: rpc.video.LikeVideoRequest
	(*LikeVideoResponse)(nil),             // 23: rpc.video.LikeVideoResponse
	(*GetUserLikedVideosRequest)(nil),     // 24: rpc.video.GetUserLikedVideosRequest
	(*GetUserLikedVideosResponse)(nil),    // 25: rpc.video.GetUserLikedVideosResponse
	(*ShareVideoRequest)(nil),             // 26: rpc.video.ShareVideoRequest
	(*ShareVideoResponse)(nil),            // 27: rpc.video.ShareVideoResponse
	(*CommentRequest)(nil),                // 28: rpc.video.CommentRequest
	(*CommentResponse)(nil),               // 29: rpc.video.CommentResponse
	(*DeleteCommentRequest)(nil),          // 30: rpc.video.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),         // 31: rpc.video.DeleteCommentResponse
	(*Video)(nil),                         // 32: rpc.video.Video
	(*User)(nil),                          // 33: rpc.user.User
}
var file_video_proto_depIdxs = []int32{
	32, // 0: rpc.video.VideoResponse.video:type_name -> rpc.video.Video
	32, // 1: rpc.video.GetVideoInfoResponse.video:type_name -> rpc.video.Video
	32, // 2: rpc.video.GetVideosByUserResponse.videos:type_name -> rpc.video.Video
	32, // 3: rpc.video.GetRecommendedVideosResponse.videos:type_name -> rpc.video.Video
	32, // 4: rpc.video.GetPersonalizedVideosResponse.videos:type_name -> rpc.video.Video
	32, // 5: rpc.video.GetFollowVideosResponse.videos:type_name -> rpc.video.Video
	32, // 6: rpc.video.GetHotVideosResponse.videos:type_name -> rpc.video.Video
	32, // 7: rpc.video.GetUserLikedVideosResponse.videos:type_name -> rpc.video.Video
	33, // 8: rpc.video.Video.author:type_name -> rpc.user.User
	2,  // 9: rpc.video.VideoService.UploadVideo:input_type -> rpc.video.UploadVideoRequest
	4,  // 10: rpc.video.VideoService.GetVideoInfo:input_type -> rpc.video.GetVideoInfoRequest
	6,  // 11: rpc.video.VideoService.GetVideosByUser:input_type -> rpc.video.GetVideosByUserRequest
	8,  // 12: rpc.video.VideoService.CreateVideo:input_type -> rpc.video.CreateVideoRequest
	10, // 13: rpc.video.VideoService.UpdateVideo:input_type -> rpc.video.UpdateVideoRequest
	12, // 14: rpc.video.VideoService.DeleteVideo:input_type -> rpc.video.DeleteVideoRequest
	14, // 15: rpc.video.VideoService.GetRecommendedVideos:input_type -> rpc.video.GetRecommendedVideosRequest
	16, // 16: rpc.video.VideoService.GetPersonalizedVideos:input_type -> rpc.video.GetPersonalizedVideosRequest
	18, // 17: rpc.video.VideoService.GetFollowVideos:input_type -> rpc.video.GetFollowVideosRequest
	20, // 18: rpc.video.VideoService.GetHotVideos:input_type -> rpc.video.GetHotVideosRequest
	22, // 19: rpc.video.VideoService.LikeVideo:input_type -> rpc.video.LikeVideoRequest
	24, // 20: rpc.video.VideoService.GetUserLikedVideos:input_type -> rpc.video.GetUserLikedVideosRequest
	26, // 21: rpc.video.VideoService.ShareVideo:input_type -> rpc.video.ShareVideoRequest
	28, // 22: rpc.video.VideoService.Comment:input_type -> rpc.video.CommentRequest
	30, // 23: rpc.video.VideoService.DeleteComment:input_type -> rpc.video.DeleteCommentRequest
	3,  // 24: rpc.video.VideoService.UploadVideo:output_type -> rpc.video.UploadVideoResponse
	5,  // 25: rpc.video.VideoService.GetVideoInfo:output_type -> rpc.video.GetVideoInfoResponse
	7,  // 26: rpc.video.VideoService.GetVideosByUser:output_type -> rpc.video.GetVideosByUserResponse
	9,  // 27: rpc.video.VideoService.CreateVideo:output_type -> rpc.video.CreateVideoResponse
	11, // 28: rpc.video.VideoService.UpdateVideo:output_type -> rpc.video.UpdateVideoResponse
	13, // 29: rpc.video.VideoService.DeleteVideo:output_type -> rpc.video.DeleteVideoResponse
	15, // 30: rpc.video.VideoService.GetRecommendedVideos:output_type -> rpc.video.GetRecommendedVideosResponse
	17, // 31: rpc.video.VideoService.GetPersonalizedVideos:output_type -> rpc.video.GetPersonalizedVideosResponse
	19, // 32: rpc.video.VideoService.GetFollowVideos:output_type -> rpc.video.GetFollowVideosResponse
	21, // 33: rpc.video.VideoService.GetHotVideos:output_type -> rpc.video.GetHotVideosResponse
	23, // 34: rpc.video.VideoService.LikeVideo:output_type -> rpc.video.LikeVideoResponse
	25, // 35: rpc.video.VideoService.GetUserLikedVideos:output_type -> rpc.video.GetUserLikedVideosResponse
	27, // 36: rpc.video.VideoService.ShareVideo:output_type -> rpc.video.ShareVideoResponse
	29, // 37: rpc.video.VideoService.Comment:output_type -> rpc.video.CommentResponse
	31, // 38: rpc.video.VideoService.DeleteComment:output_type -> rpc.video.DeleteCommentResponse
	24, // [24:39] is the sub-list for method output_type
	9,  // [9:24] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
