# user-service配置文件
server:
  host: 0.0.0.0
  port: 50051
  mode: debug

database:
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: vision_world
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

logger:
  level: info
  format: json
  output_path: logs/user-service.log

consul:
  host: localhost
  port: 8500
  health_check:
    interval: 10s
    timeout: 5s

etcd:
  endpoints:
    - localhost:2379
  dial_timeout: 5s
  username: ""
  password: ""

jwt:
  secret_key: "your-secret-key-here"
  expire_hours: 24

sms:
  access_key: "your-access-key"
  secret_key: "your-secret-key"
  sign_name: "VisionWorld"
  template_code: "SMS_123456789"