// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.1
// source: proto_defs/recommendation.proto

package recommendation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取个性化推荐请求
type GetPersonalizedRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                           // 页码
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每页数量
	Category      *string                `protobuf:"bytes,4,opt,name=category,proto3,oneof" json:"category,omitempty"`              // 分类筛选
	UserTags      string                 `protobuf:"bytes,5,opt,name=user_tags,json=userTags,proto3" json:"user_tags,omitempty"`    // 用户标签
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalizedRecommendationsRequest) Reset() {
	*x = GetPersonalizedRecommendationsRequest{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalizedRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalizedRecommendationsRequest) ProtoMessage() {}

func (x *GetPersonalizedRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalizedRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetPersonalizedRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *GetPersonalizedRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPersonalizedRecommendationsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPersonalizedRecommendationsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPersonalizedRecommendationsRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *GetPersonalizedRecommendationsRequest) GetUserTags() string {
	if x != nil {
		return x.UserTags
	}
	return ""
}

func (x *GetPersonalizedRecommendationsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 获取个性化推荐响应
type GetPersonalizedRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态消息
	Videos        []*Video               `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`                            // 视频列表
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`          // 是否有更多
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalizedRecommendationsResponse) Reset() {
	*x = GetPersonalizedRecommendationsResponse{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalizedRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalizedRecommendationsResponse) ProtoMessage() {}

func (x *GetPersonalizedRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalizedRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetPersonalizedRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *GetPersonalizedRecommendationsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetPersonalizedRecommendationsResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetPersonalizedRecommendationsResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetPersonalizedRecommendationsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 获取通用推荐请求
type GetGeneralRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                           // 页码
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每页数量
	Category      *string                `protobuf:"bytes,3,opt,name=category,proto3,oneof" json:"category,omitempty"`              // 分类筛选
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneralRecommendationsRequest) Reset() {
	*x = GetGeneralRecommendationsRequest{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneralRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneralRecommendationsRequest) ProtoMessage() {}

func (x *GetGeneralRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneralRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetGeneralRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *GetGeneralRecommendationsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGeneralRecommendationsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetGeneralRecommendationsRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *GetGeneralRecommendationsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 获取通用推荐响应
type GetGeneralRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态消息
	Videos        []*Video               `protobuf:"bytes,3,rep,name=videos,proto3" json:"videos,omitempty"`                            // 视频列表
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`          // 是否有更多
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneralRecommendationsResponse) Reset() {
	*x = GetGeneralRecommendationsResponse{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneralRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneralRecommendationsResponse) ProtoMessage() {}

func (x *GetGeneralRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneralRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetGeneralRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *GetGeneralRecommendationsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetGeneralRecommendationsResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetGeneralRecommendationsResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetGeneralRecommendationsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 更新用户偏好请求
type UpdateUserPreferencesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                                                        // 用户ID
	Categories      []string               `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`                                                                                                              // 偏好分类
	Tags            []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                                                          // 偏好标签
	CategoryWeights map[string]float32     `protobuf:"bytes,4,rep,name=category_weights,json=categoryWeights,proto3" json:"category_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // 分类权重
	TagWeights      map[string]float32     `protobuf:"bytes,5,rep,name=tag_weights,json=tagWeights,proto3" json:"tag_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`                // 标签权重
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserPreferencesRequest) Reset() {
	*x = UpdateUserPreferencesRequest{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesRequest) ProtoMessage() {}

func (x *UpdateUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *UpdateUserPreferencesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateUserPreferencesRequest) GetCategoryWeights() map[string]float32 {
	if x != nil {
		return x.CategoryWeights
	}
	return nil
}

func (x *UpdateUserPreferencesRequest) GetTagWeights() map[string]float32 {
	if x != nil {
		return x.TagWeights
	}
	return nil
}

// 更新用户偏好响应
type UpdateUserPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPreferencesResponse) Reset() {
	*x = UpdateUserPreferencesResponse{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesResponse) ProtoMessage() {}

func (x *UpdateUserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserPreferencesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateUserPreferencesResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// 记录用户行为请求
type RecordUserActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // 用户ID
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                     // 视频ID
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`            // 行为类型 (view, like, share, comment, complete)
	Duration      float32                `protobuf:"fixed32,4,opt,name=duration,proto3" json:"duration,omitempty"`                                // 观看时长（秒）
	TotalDuration float32                `protobuf:"fixed32,5,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"` // 视频总时长（秒）
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                               // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUserActionRequest) Reset() {
	*x = RecordUserActionRequest{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUserActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUserActionRequest) ProtoMessage() {}

func (x *RecordUserActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUserActionRequest.ProtoReflect.Descriptor instead.
func (*RecordUserActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{6}
}

func (x *RecordUserActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordUserActionRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *RecordUserActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *RecordUserActionRequest) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RecordUserActionRequest) GetTotalDuration() float32 {
	if x != nil {
		return x.TotalDuration
	}
	return 0
}

func (x *RecordUserActionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 记录用户行为响应
type RecordUserActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUserActionResponse) Reset() {
	*x = RecordUserActionResponse{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUserActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUserActionResponse) ProtoMessage() {}

func (x *RecordUserActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUserActionResponse.ProtoReflect.Descriptor instead.
func (*RecordUserActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{7}
}

func (x *RecordUserActionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RecordUserActionResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// 视频信息
type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                 // 视频ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                    // 标题
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                        // 描述
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`              // 封面URL
	VideoUrl      string                 `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`              // 视频URL
	Duration      uint32                 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`                             // 时长（秒）
	ViewCount     uint32                 `protobuf:"varint,7,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`          // 观看次数
	LikeCount     uint32                 `protobuf:"varint,8,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞数
	CommentCount  uint32                 `protobuf:"varint,9,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论数
	ShareCount    uint32                 `protobuf:"varint,10,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`      // 分享数
	AuthorId      string                 `protobuf:"bytes,11,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`             // 作者ID
	AuthorName    string                 `protobuf:"bytes,12,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`       // 作者名称
	AuthorAvatar  string                 `protobuf:"bytes,13,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"` // 作者头像
	Tags          []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`                                     // 标签
	Category      string                 `protobuf:"bytes,15,opt,name=category,proto3" json:"category,omitempty"`                             // 分类
	CreateTime    int64                  `protobuf:"varint,16,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`      // 创建时间
	Score         float32                `protobuf:"fixed32,17,opt,name=score,proto3" json:"score,omitempty"`                                 // 推荐分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_proto_defs_recommendation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_defs_recommendation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_proto_defs_recommendation_proto_rawDescGZIP(), []int{8}
}

func (x *Video) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Video) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Video) GetViewCount() uint32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Video) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Video) GetCommentCount() uint32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetShareCount() uint32 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Video) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Video) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Video) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

func (x *Video) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Video) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Video) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Video) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_proto_defs_recommendation_proto protoreflect.FileDescriptor

const file_proto_defs_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x1fproto_defs/recommendation.proto\x12\x0erecommendation\"\xdb\x01\n" +
	"%GetPersonalizedRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x1f\n" +
	"\bcategory\x18\x04 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\x1b\n" +
	"\tuser_tags\x18\x05 \x01(\tR\buserTags\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestIdB\v\n" +
	"\t_category\"\xb2\x01\n" +
	"&GetPersonalizedRecommendationsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12-\n" +
	"\x06videos\x18\x03 \x03(\v2\x15.recommendation.VideoR\x06videos\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xa0\x01\n" +
	" GetGeneralRecommendationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1f\n" +
	"\bcategory\x18\x03 \x01(\tH\x00R\bcategory\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestIdB\v\n" +
	"\t_category\"\xad\x01\n" +
	"!GetGeneralRecommendationsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12-\n" +
	"\x06videos\x18\x03 \x03(\v2\x15.recommendation.VideoR\x06videos\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xbb\x03\n" +
	"\x1cUpdateUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"categories\x18\x02 \x03(\tR\n" +
	"categories\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12l\n" +
	"\x10category_weights\x18\x04 \x03(\v2A.recommendation.UpdateUserPreferencesRequest.CategoryWeightsEntryR\x0fcategoryWeights\x12]\n" +
	"\vtag_weights\x18\x05 \x03(\v2<.recommendation.UpdateUserPreferencesRequest.TagWeightsEntryR\n" +
	"tagWeights\x1aB\n" +
	"\x14CategoryWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a=\n" +
	"\x0fTagWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"_\n" +
	"\x1dUpdateUserPreferencesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"\xcf\x01\n" +
	"\x17RecordUserActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x02R\bduration\x12%\n" +
	"\x0etotal_duration\x18\x05 \x01(\x02R\rtotalDuration\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"Z\n" +
	"\x18RecordUserActionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"\xfe\x03\n" +
	"\x05Video\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tvideo_url\x18\x05 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\rR\bduration\x12\x1d\n" +
	"\n" +
	"view_count\x18\a \x01(\rR\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\b \x01(\rR\tlikeCount\x12#\n" +
	"\rcomment_count\x18\t \x01(\rR\fcommentCount\x12\x1f\n" +
	"\vshare_count\x18\n" +
	" \x01(\rR\n" +
	"shareCount\x12\x1b\n" +
	"\tauthor_id\x18\v \x01(\tR\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\f \x01(\tR\n" +
	"authorName\x12#\n" +
	"\rauthor_avatar\x18\r \x01(\tR\fauthorAvatar\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x1a\n" +
	"\bcategory\x18\x0f \x01(\tR\bcategory\x12\x1f\n" +
	"\vcreate_time\x18\x10 \x01(\x03R\n" +
	"createTime\x12\x14\n" +
	"\x05score\x18\x11 \x01(\x02R\x05score2\x89\x04\n" +
	"\x15RecommendationService\x12\x8f\x01\n" +
	"\x1eGetPersonalizedRecommendations\x125.recommendation.GetPersonalizedRecommendationsRequest\x1a6.recommendation.GetPersonalizedRecommendationsResponse\x12\x80\x01\n" +
	"\x19GetGeneralRecommendations\x120.recommendation.GetGeneralRecommendationsRequest\x1a1.recommendation.GetGeneralRecommendationsResponse\x12t\n" +
	"\x15UpdateUserPreferences\x12,.recommendation.UpdateUserPreferencesRequest\x1a-.recommendation.UpdateUserPreferencesResponse\x12e\n" +
	"\x10RecordUserAction\x12'.recommendation.RecordUserActionRequest\x1a(.recommendation.RecordUserActionResponseB>Z<github.com/vision_world/api_gateway/proto_gen/recommendationb\x06proto3"

var (
	file_proto_defs_recommendation_proto_rawDescOnce sync.Once
	file_proto_defs_recommendation_proto_rawDescData []byte
)

func file_proto_defs_recommendation_proto_rawDescGZIP() []byte {
	file_proto_defs_recommendation_proto_rawDescOnce.Do(func() {
		file_proto_defs_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_defs_recommendation_proto_rawDesc), len(file_proto_defs_recommendation_proto_rawDesc)))
	})
	return file_proto_defs_recommendation_proto_rawDescData
}

var file_proto_defs_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_defs_recommendation_proto_goTypes = []any{
	(*GetPersonalizedRecommendationsRequest)(nil),  // 0: recommendation.GetPersonalizedRecommendationsRequest
	(*GetPersonalizedRecommendationsResponse)(nil), // 1: recommendation.GetPersonalizedRecommendationsResponse
	(*GetGeneralRecommendationsRequest)(nil),       // 2: recommendation.GetGeneralRecommendationsRequest
	(*GetGeneralRecommendationsResponse)(nil),      // 3: recommendation.GetGeneralRecommendationsResponse
	(*UpdateUserPreferencesRequest)(nil),           // 4: recommendation.UpdateUserPreferencesRequest
	(*UpdateUserPreferencesResponse)(nil),          // 5: recommendation.UpdateUserPreferencesResponse
	(*RecordUserActionRequest)(nil),                // 6: recommendation.RecordUserActionRequest
	(*RecordUserActionResponse)(nil),               // 7: recommendation.RecordUserActionResponse
	(*Video)(nil),                                  // 8: recommendation.Video
	nil,                                            // 9: recommendation.UpdateUserPreferencesRequest.CategoryWeightsEntry
	nil,                                            // 10: recommendation.UpdateUserPreferencesRequest.TagWeightsEntry
}
var file_proto_defs_recommendation_proto_depIdxs = []int32{
	8,  // 0: recommendation.GetPersonalizedRecommendationsResponse.videos:type_name -> recommendation.Video
	8,  // 1: recommendation.GetGeneralRecommendationsResponse.videos:type_name -> recommendation.Video
	9,  // 2: recommendation.UpdateUserPreferencesRequest.category_weights:type_name -> recommendation.UpdateUserPreferencesRequest.CategoryWeightsEntry
	10, // 3: recommendation.UpdateUserPreferencesRequest.tag_weights:type_name -> recommendation.UpdateUserPreferencesRequest.TagWeightsEntry
	0,  // 4: recommendation.RecommendationService.GetPersonalizedRecommendations:input_type -> recommendation.GetPersonalizedRecommendationsRequest
	2,  // 5: recommendation.RecommendationService.GetGeneralRecommendations:input_type -> recommendation.GetGeneralRecommendationsRequest
	4,  // 6: recommendation.RecommendationService.UpdateUserPreferences:input_type -> recommendation.UpdateUserPreferencesRequest
	6,  // 7: recommendation.RecommendationService.RecordUserAction:input_type -> recommendation.RecordUserActionRequest
	1,  // 8: recommendation.RecommendationService.GetPersonalizedRecommendations:output_type -> recommendation.GetPersonalizedRecommendationsResponse
	3,  // 9: recommendation.RecommendationService.GetGeneralRecommendations:output_type -> recommendation.GetGeneralRecommendationsResponse
	5,  // 10: recommendation.RecommendationService.UpdateUserPreferences:output_type -> recommendation.UpdateUserPreferencesResponse
	7,  // 11: recommendation.RecommendationService.RecordUserAction:output_type -> recommendation.RecordUserActionResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_defs_recommendation_proto_init() }
func file_proto_defs_recommendation_proto_init() {
	if File_proto_defs_recommendation_proto != nil {
		return
	}
	file_proto_defs_recommendation_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_defs_recommendation_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_defs_recommendation_proto_rawDesc), len(file_proto_defs_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_defs_recommendation_proto_goTypes,
		DependencyIndexes: file_proto_defs_recommendation_proto_depIdxs,
		MessageInfos:      file_proto_defs_recommendation_proto_msgTypes,
	}.Build()
	File_proto_defs_recommendation_proto = out.File
	file_proto_defs_recommendation_proto_goTypes = nil
	file_proto_defs_recommendation_proto_depIdxs = nil
}
