// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.1
// source: proto_defs/recommendation.proto

package recommendation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RecommendationService_GetPersonalizedRecommendations_FullMethodName = "/recommendation.RecommendationService/GetPersonalizedRecommendations"
	RecommendationService_GetGeneralRecommendations_FullMethodName      = "/recommendation.RecommendationService/GetGeneralRecommendations"
	RecommendationService_UpdateUserPreferences_FullMethodName          = "/recommendation.RecommendationService/UpdateUserPreferences"
	RecommendationService_RecordUserAction_FullMethodName               = "/recommendation.RecommendationService/RecordUserAction"
)

// RecommendationServiceClient is the client API for RecommendationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendationServiceClient interface {
	// 获取个性化推荐
	GetPersonalizedRecommendations(ctx context.Context, in *GetPersonalizedRecommendationsRequest, opts ...grpc.CallOption) (*GetPersonalizedRecommendationsResponse, error)
	// 获取通用推荐
	GetGeneralRecommendations(ctx context.Context, in *GetGeneralRecommendationsRequest, opts ...grpc.CallOption) (*GetGeneralRecommendationsResponse, error)
	// 更新用户偏好
	UpdateUserPreferences(ctx context.Context, in *UpdateUserPreferencesRequest, opts ...grpc.CallOption) (*UpdateUserPreferencesResponse, error)
	// 记录用户行为
	RecordUserAction(ctx context.Context, in *RecordUserActionRequest, opts ...grpc.CallOption) (*RecordUserActionResponse, error)
}

type recommendationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationServiceClient(cc grpc.ClientConnInterface) RecommendationServiceClient {
	return &recommendationServiceClient{cc}
}

func (c *recommendationServiceClient) GetPersonalizedRecommendations(ctx context.Context, in *GetPersonalizedRecommendationsRequest, opts ...grpc.CallOption) (*GetPersonalizedRecommendationsResponse, error) {
	out := new(GetPersonalizedRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetPersonalizedRecommendations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) GetGeneralRecommendations(ctx context.Context, in *GetGeneralRecommendationsRequest, opts ...grpc.CallOption) (*GetGeneralRecommendationsResponse, error) {
	out := new(GetGeneralRecommendationsResponse)
	err := c.cc.Invoke(ctx, RecommendationService_GetGeneralRecommendations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) UpdateUserPreferences(ctx context.Context, in *UpdateUserPreferencesRequest, opts ...grpc.CallOption) (*UpdateUserPreferencesResponse, error) {
	out := new(UpdateUserPreferencesResponse)
	err := c.cc.Invoke(ctx, RecommendationService_UpdateUserPreferences_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendationServiceClient) RecordUserAction(ctx context.Context, in *RecordUserActionRequest, opts ...grpc.CallOption) (*RecordUserActionResponse, error) {
	out := new(RecordUserActionResponse)
	err := c.cc.Invoke(ctx, RecommendationService_RecordUserAction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServiceServer is the server API for RecommendationService service.
// All implementations must embed UnimplementedRecommendationServiceServer
// for forward compatibility
type RecommendationServiceServer interface {
	// 获取个性化推荐
	GetPersonalizedRecommendations(context.Context, *GetPersonalizedRecommendationsRequest) (*GetPersonalizedRecommendationsResponse, error)
	// 获取通用推荐
	GetGeneralRecommendations(context.Context, *GetGeneralRecommendationsRequest) (*GetGeneralRecommendationsResponse, error)
	// 更新用户偏好
	UpdateUserPreferences(context.Context, *UpdateUserPreferencesRequest) (*UpdateUserPreferencesResponse, error)
	// 记录用户行为
	RecordUserAction(context.Context, *RecordUserActionRequest) (*RecordUserActionResponse, error)
	mustEmbedUnimplementedRecommendationServiceServer()
}

// UnimplementedRecommendationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRecommendationServiceServer struct {
}

func (UnimplementedRecommendationServiceServer) GetPersonalizedRecommendations(context.Context, *GetPersonalizedRecommendationsRequest) (*GetPersonalizedRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonalizedRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) GetGeneralRecommendations(context.Context, *GetGeneralRecommendationsRequest) (*GetGeneralRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeneralRecommendations not implemented")
}
func (UnimplementedRecommendationServiceServer) UpdateUserPreferences(context.Context, *UpdateUserPreferencesRequest) (*UpdateUserPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPreferences not implemented")
}
func (UnimplementedRecommendationServiceServer) RecordUserAction(context.Context, *RecordUserActionRequest) (*RecordUserActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordUserAction not implemented")
}
func (UnimplementedRecommendationServiceServer) mustEmbedUnimplementedRecommendationServiceServer() {}

// UnsafeRecommendationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationServiceServer will
// result in compilation errors.
type UnsafeRecommendationServiceServer interface {
	mustEmbedUnimplementedRecommendationServiceServer()
}

func RegisterRecommendationServiceServer(s grpc.ServiceRegistrar, srv RecommendationServiceServer) {
	s.RegisterService(&RecommendationService_ServiceDesc, srv)
}

func _RecommendationService_GetPersonalizedRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonalizedRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetPersonalizedRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetPersonalizedRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetPersonalizedRecommendations(ctx, req.(*GetPersonalizedRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_GetGeneralRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeneralRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).GetGeneralRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_GetGeneralRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).GetGeneralRecommendations(ctx, req.(*GetGeneralRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_UpdateUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).UpdateUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_UpdateUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).UpdateUserPreferences(ctx, req.(*UpdateUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendationService_RecordUserAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordUserActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServiceServer).RecordUserAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendationService_RecordUserAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServiceServer).RecordUserAction(ctx, req.(*RecordUserActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendationService_ServiceDesc is the grpc.ServiceDesc for RecommendationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recommendation.RecommendationService",
	HandlerType: (*RecommendationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersonalizedRecommendations",
			Handler:    _RecommendationService_GetPersonalizedRecommendations_Handler,
		},
		{
			MethodName: "GetGeneralRecommendations",
			Handler:    _RecommendationService_GetGeneralRecommendations_Handler,
		},
		{
			MethodName: "UpdateUserPreferences",
			Handler:    _RecommendationService_UpdateUserPreferences_Handler,
		},
		{
			MethodName: "RecordUserAction",
			Handler:    _RecommendationService_RecordUserAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto_defs/recommendation.proto",
}
