// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.1
// source: danmaku.proto

package danmaku

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送弹幕请求
type SendDanmakuRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        uint32                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                       // 视频ID
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                             // 弹幕内容
	Color          string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`                                           // 弹幕颜色，默认为白色
	VideoTimestamp float32                `protobuf:"fixed32,4,opt,name=video_timestamp,json=videoTimestamp,proto3" json:"video_timestamp,omitempty"` // 视频时间戳（秒）
	Speed          string                 `protobuf:"bytes,5,opt,name=speed,proto3" json:"speed,omitempty"`                                           // 弹幕速度：slow, normal, fast
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendDanmakuRequest) Reset() {
	*x = SendDanmakuRequest{}
	mi := &file_danmaku_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDanmakuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDanmakuRequest) ProtoMessage() {}

func (x *SendDanmakuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDanmakuRequest.ProtoReflect.Descriptor instead.
func (*SendDanmakuRequest) Descriptor() ([]byte, []int) {
	return file_danmaku_proto_rawDescGZIP(), []int{0}
}

func (x *SendDanmakuRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SendDanmakuRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendDanmakuRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *SendDanmakuRequest) GetVideoTimestamp() float32 {
	if x != nil {
		return x.VideoTimestamp
	}
	return 0
}

func (x *SendDanmakuRequest) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

// 发送弹幕响应
type SendDanmakuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	Danmaku       *Danmaku               `protobuf:"bytes,3,opt,name=danmaku,proto3" json:"danmaku,omitempty"`  // 发送的弹幕信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDanmakuResponse) Reset() {
	*x = SendDanmakuResponse{}
	mi := &file_danmaku_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDanmakuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDanmakuResponse) ProtoMessage() {}

func (x *SendDanmakuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDanmakuResponse.ProtoReflect.Descriptor instead.
func (*SendDanmakuResponse) Descriptor() ([]byte, []int) {
	return file_danmaku_proto_rawDescGZIP(), []int{1}
}

func (x *SendDanmakuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendDanmakuResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendDanmakuResponse) GetDanmaku() *Danmaku {
	if x != nil {
		return x.Danmaku
	}
	return nil
}

// 获取弹幕列表请求
type GetDanmakusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint32                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`    // 视频ID
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页码，默认1
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量，默认20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDanmakusRequest) Reset() {
	*x = GetDanmakusRequest{}
	mi := &file_danmaku_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDanmakusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDanmakusRequest) ProtoMessage() {}

func (x *GetDanmakusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDanmakusRequest.ProtoReflect.Descriptor instead.
func (*GetDanmakusRequest) Descriptor() ([]byte, []int) {
	return file_danmaku_proto_rawDescGZIP(), []int{2}
}

func (x *GetDanmakusRequest) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetDanmakusRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDanmakusRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取弹幕列表响应
type GetDanmakusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Danmakus      []*Danmaku             `protobuf:"bytes,1,rep,name=danmakus,proto3" json:"danmakus,omitempty"` // 弹幕列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`      // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDanmakusResponse) Reset() {
	*x = GetDanmakusResponse{}
	mi := &file_danmaku_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDanmakusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDanmakusResponse) ProtoMessage() {}

func (x *GetDanmakusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDanmakusResponse.ProtoReflect.Descriptor instead.
func (*GetDanmakusResponse) Descriptor() ([]byte, []int) {
	return file_danmaku_proto_rawDescGZIP(), []int{3}
}

func (x *GetDanmakusResponse) GetDanmakus() []*Danmaku {
	if x != nil {
		return x.Danmakus
	}
	return nil
}

func (x *GetDanmakusResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 弹幕信息
type Danmaku struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                // 弹幕ID
	UserId         uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          // 用户ID
	VideoId        uint32                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`                       // 视频ID
	Text           string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`                                             // 弹幕内容
	Color          string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`                                           // 弹幕颜色
	VideoTimestamp float32                `protobuf:"fixed32,6,opt,name=video_timestamp,json=videoTimestamp,proto3" json:"video_timestamp,omitempty"` // 视频时间戳（秒）
	Speed          string                 `protobuf:"bytes,7,opt,name=speed,proto3" json:"speed,omitempty"`                                           // 弹幕速度
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // 创建时间戳（秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Danmaku) Reset() {
	*x = Danmaku{}
	mi := &file_danmaku_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Danmaku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Danmaku) ProtoMessage() {}

func (x *Danmaku) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Danmaku.ProtoReflect.Descriptor instead.
func (*Danmaku) Descriptor() ([]byte, []int) {
	return file_danmaku_proto_rawDescGZIP(), []int{4}
}

func (x *Danmaku) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Danmaku) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Danmaku) GetVideoId() uint32 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Danmaku) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Danmaku) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Danmaku) GetVideoTimestamp() float32 {
	if x != nil {
		return x.VideoTimestamp
	}
	return 0
}

func (x *Danmaku) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

func (x *Danmaku) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_danmaku_proto protoreflect.FileDescriptor

const file_danmaku_proto_rawDesc = "" +
	"\n" +
	"\rdanmaku.proto\x12\adanmaku\"\x98\x01\n" +
	"\x12SendDanmakuRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\rR\avideoId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12'\n" +
	"\x0fvideo_timestamp\x18\x04 \x01(\x02R\x0evideoTimestamp\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\tR\x05speed\"u\n" +
	"\x13SendDanmakuResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\adanmaku\x18\x03 \x01(\v2\x10.danmaku.DanmakuR\adanmaku\"`\n" +
	"\x12GetDanmakusRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\rR\avideoId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Y\n" +
	"\x13GetDanmakusResponse\x12,\n" +
	"\bdanmakus\x18\x01 \x03(\v2\x10.danmaku.DanmakuR\bdanmakus\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd5\x01\n" +
	"\aDanmaku\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\rR\avideoId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12'\n" +
	"\x0fvideo_timestamp\x18\x06 \x01(\x02R\x0evideoTimestamp\x12\x14\n" +
	"\x05speed\x18\a \x01(\tR\x05speed\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt2\xa4\x01\n" +
	"\x0eDanmakuService\x12H\n" +
	"\vSendDanmaku\x12\x1b.danmaku.SendDanmakuRequest\x1a\x1c.danmaku.SendDanmakuResponse\x12H\n" +
	"\vGetDanmakus\x12\x1b.danmaku.GetDanmakusRequest\x1a\x1c.danmaku.GetDanmakusResponseB\x15Z\x13./proto_gen/danmakub\x06proto3"

var (
	file_danmaku_proto_rawDescOnce sync.Once
	file_danmaku_proto_rawDescData []byte
)

func file_danmaku_proto_rawDescGZIP() []byte {
	file_danmaku_proto_rawDescOnce.Do(func() {
		file_danmaku_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_danmaku_proto_rawDesc), len(file_danmaku_proto_rawDesc)))
	})
	return file_danmaku_proto_rawDescData
}

var file_danmaku_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_danmaku_proto_goTypes = []any{
	(*SendDanmakuRequest)(nil),  // 0: danmaku.SendDanmakuRequest
	(*SendDanmakuResponse)(nil), // 1: danmaku.SendDanmakuResponse
	(*GetDanmakusRequest)(nil),  // 2: danmaku.GetDanmakusRequest
	(*GetDanmakusResponse)(nil), // 3: danmaku.GetDanmakusResponse
	(*Danmaku)(nil),             // 4: danmaku.Danmaku
}
var file_danmaku_proto_depIdxs = []int32{
	4, // 0: danmaku.SendDanmakuResponse.danmaku:type_name -> danmaku.Danmaku
	4, // 1: danmaku.GetDanmakusResponse.danmakus:type_name -> danmaku.Danmaku
	0, // 2: danmaku.DanmakuService.SendDanmaku:input_type -> danmaku.SendDanmakuRequest
	2, // 3: danmaku.DanmakuService.GetDanmakus:input_type -> danmaku.GetDanmakusRequest
	1, // 4: danmaku.DanmakuService.SendDanmaku:output_type -> danmaku.SendDanmakuResponse
	3, // 5: danmaku.DanmakuService.GetDanmakus:output_type -> danmaku.GetDanmakusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_danmaku_proto_init() }
func file_danmaku_proto_init() {
	if File_danmaku_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_danmaku_proto_rawDesc), len(file_danmaku_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_danmaku_proto_goTypes,
		DependencyIndexes: file_danmaku_proto_depIdxs,
		MessageInfos:      file_danmaku_proto_msgTypes,
	}.Build()
	File_danmaku_proto = out.File
	file_danmaku_proto_goTypes = nil
	file_danmaku_proto_depIdxs = nil
}
