// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.1
// source: danmaku.proto

package danmaku

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DanmakuService_SendDanmaku_FullMethodName = "/danmaku.DanmakuService/SendDanmaku"
	DanmakuService_GetDanmakus_FullMethodName = "/danmaku.DanmakuService/GetDanmakus"
)

// DanmakuServiceClient is the client API for DanmakuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DanmakuServiceClient interface {
	// 发送弹幕
	SendDanmaku(ctx context.Context, in *SendDanmakuRequest, opts ...grpc.CallOption) (*SendDanmakuResponse, error)
	// 获取视频弹幕列表
	GetDanmakus(ctx context.Context, in *GetDanmakusRequest, opts ...grpc.CallOption) (*GetDanmakusResponse, error)
}

type danmakuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDanmakuServiceClient(cc grpc.ClientConnInterface) DanmakuServiceClient {
	return &danmakuServiceClient{cc}
}

func (c *danmakuServiceClient) SendDanmaku(ctx context.Context, in *SendDanmakuRequest, opts ...grpc.CallOption) (*SendDanmakuResponse, error) {
	out := new(SendDanmakuResponse)
	err := c.cc.Invoke(ctx, DanmakuService_SendDanmaku_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *danmakuServiceClient) GetDanmakus(ctx context.Context, in *GetDanmakusRequest, opts ...grpc.CallOption) (*GetDanmakusResponse, error) {
	out := new(GetDanmakusResponse)
	err := c.cc.Invoke(ctx, DanmakuService_GetDanmakus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DanmakuServiceServer is the server API for DanmakuService service.
// All implementations must embed UnimplementedDanmakuServiceServer
// for forward compatibility
type DanmakuServiceServer interface {
	// 发送弹幕
	SendDanmaku(context.Context, *SendDanmakuRequest) (*SendDanmakuResponse, error)
	// 获取视频弹幕列表
	GetDanmakus(context.Context, *GetDanmakusRequest) (*GetDanmakusResponse, error)
	mustEmbedUnimplementedDanmakuServiceServer()
}

// UnimplementedDanmakuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDanmakuServiceServer struct {
}

func (UnimplementedDanmakuServiceServer) SendDanmaku(context.Context, *SendDanmakuRequest) (*SendDanmakuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDanmaku not implemented")
}
func (UnimplementedDanmakuServiceServer) GetDanmakus(context.Context, *GetDanmakusRequest) (*GetDanmakusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDanmakus not implemented")
}
func (UnimplementedDanmakuServiceServer) mustEmbedUnimplementedDanmakuServiceServer() {}

// UnsafeDanmakuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DanmakuServiceServer will
// result in compilation errors.
type UnsafeDanmakuServiceServer interface {
	mustEmbedUnimplementedDanmakuServiceServer()
}

func RegisterDanmakuServiceServer(s grpc.ServiceRegistrar, srv DanmakuServiceServer) {
	s.RegisterService(&DanmakuService_ServiceDesc, srv)
}

func _DanmakuService_SendDanmaku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDanmakuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DanmakuServiceServer).SendDanmaku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DanmakuService_SendDanmaku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DanmakuServiceServer).SendDanmaku(ctx, req.(*SendDanmakuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DanmakuService_GetDanmakus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDanmakusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DanmakuServiceServer).GetDanmakus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DanmakuService_GetDanmakus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DanmakuServiceServer).GetDanmakus(ctx, req.(*GetDanmakusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DanmakuService_ServiceDesc is the grpc.ServiceDesc for DanmakuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DanmakuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "danmaku.DanmakuService",
	HandlerType: (*DanmakuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDanmaku",
			Handler:    _DanmakuService_SendDanmaku_Handler,
		},
		{
			MethodName: "GetDanmakus",
			Handler:    _DanmakuService_GetDanmakus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "danmaku.proto",
}
